config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :homes do
   resources :homecomments
   end

   resources :shops do
   resources :shopcomments
   end
   resources :profiles
   resources :products  
   resources :messages
   get '/user' => 'homes#user'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord

belongs_to :user
has_many :homecomments,dependent: :destroy


has_attached_file :homeimage, styles: { medium: "320x320>", thumb: "100x100>" }
validates_attachment_content_type :homeimage, content_type: /\Aimage\/.*\z/


def self.search(search)
  if search
  self.where("LOWER(product_name) LIKE ?", "%#{search}%")
  else
  self.all
  end
end
 end

app/models/homecomment.rb
class Homecomment < ApplicationRecord
  belongs_to :home
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord

def message_shops
shops =Shop.where("shop_name LIKE '%#{keywords}%' AND shop_city LIKE '%#{keywords2}%' AND shop_type LIKE '%#{keywords3}%'") if keywords||keywords2||keywords3.present?

return shops

end

end

app/models/product.rb
class Product < ApplicationRecord
belongs_to :user
has_attached_file :product_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :product_image, content_type: /\Aimage\/.*\z/
end

app/models/profile.rb
class Profile < ApplicationRecord

belongs_to :user
has_attached_file :profile_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :profile_image, content_type: /\Aimage\/.*\z/
end

app/models/shop.rb
class Shop < ApplicationRecord
belongs_to :user
has_many :shopcomments,dependent: :destroy

has_attached_file :shop_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :shop_image, content_type: /\Aimage\/.*\z/


def self.search(search)
  if search
  self.where("shop_name like ?", "%#{search}%")
  else
  self.all
  end
end


end

app/models/shopcomment.rb
class Shopcomment < ApplicationRecord
  belongs_to :shop
  belongs_to :user
end
 

app/models/user.rb
class User < ApplicationRecord
has_many :homes
has_many :homecomments
has_many :shops
has_many :shopcomments
has_many :profiles
has_many :products
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

def self.search(search)
  if search
  self.where("name like ?", "%#{search}%")
  else
  self.all
  end
end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception
before_action :configure_permitted_parameters, if: :devise_controller?	

def check_is_admin
 	
 	if current_user.is_admin
return true
else
	redirect_to homes_path,notice:"page looking for sign_in"
end
end

private

 
def after_sign_out_path_for(resource_or_scope)
  new_user_session_path
end


def after_sign_in_path_for(resource_or_scope)
  homes_path
end

protected

def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:country,:business_type,:mobile_number])
   devise_parameter_sanitizer.permit(:account_update, keys: [:country,:business_type,:mobile_number]) 
end
end

app/controllers/homes_controller.rb
 class HomesController < ApplicationController

before_action :find_home, only: [:show, :edit, :update, :destroy]

def index   
 @homes = Home.order(created_at: :desc).search(params[:search])
 @home = Home.new
 @users = User.all
end


def new
@profile = Profile.all
@users = User.order(created_at: :desc).search(params[:search])
end


def create
    @home = current_user.homes.build(home_params)
    if @home.save
       redirect_to homes_path 
     
  end
end

def show
    
 
    
end


def edit
 	   
end

def update
		
     
	if @home.update(home_params)
			redirect_to home_path
		else
			render 'edit'
		end

end

def destroy
	
	@home.destroy
	redirect_to homes_path
end	

private

def home_params
			
	params.require(:home).permit(:product_name,:homeimage,:description,:market_type)

end

def find_home
    	 
    @home = Home.find(params[:id])
 

   
end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def new
	@message = Message.new
	@shop = Shop.all

	 if params[:keyword].present? 
        @shops = @shops.by_keyword(params[:keyword])
end
end
def create
	@message = Message.create(message_params)
	redirect_to @message
	
end

def show
    @message = Message.new
	@message = Message.find(params[:id])
end

private

def message_params
	params.require(:message).permit(:keywords,:keywords2,:keywords3)
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 before_action :find_product, only: [:show, :edit, :update, :destroy]

def index
	
end

def new


end

def create
  @product = current_user.products.build(product_params)
  if @product.save
  redirect_to product_path(@product.user.id)

else
  render "new"
  end
end	


def show
  @product = Product.new
  @user = User.find(params[:id])	
  @shop = Shop.where(params[:id])

 
end

def edit
	
end

def update
	
end

def destroy
  @product = Product.find(params[:id])
  @product.destroy
  redirect_to product_path(@product.user.id)
 end	
	
end

private

def product_params
    
  params.require(:product).permit(:product_name,:product_price,:product_image)
    
end

def find_product

  @products = Product.where(params[:id])

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 before_action :find_profile, only: [:show, :edit, :update, :destroy]

def index
@users = User.includes(:homes,:homecomments)
end

def new

@profile = current_user.profiles.build

end

def create
  @profile = current_user.profiles.build(profile_params)
  if @profile.save
  redirect_to profile_path(@profile.user.id)
  else
  render "new"
  end
end	

def show
  @user = User.find(params[:id])	
  @shop = Shop.where(params[:id])
  @product = Product.where(params[:id])
end

def edit
	
end

def update
	
end

def destroy
  @profile = Profile.find(params[:id])
  @profile.destroy
  redirect_to profile_path(@profile.user.id)
 end	
	
end

private

def profile_params
    
  params.require(:profile).permit(:profile_image,:date_of_birth)
    
end

def find_profile

  @profiles = Profile.where(params[:id])

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
 before_action :find_shop, only: [:show, :edit, :update, :destroy]

def index
@shop = Shop.order(created_at: :desc).search(params[:search])
end

def new

@shop = current_user.shops.build

end

def create
  @shop = current_user.shops.build(shop_params)
  if @shop.save
  redirect_to profile_path(@shop.user.id)

else
  render "new"
  end
end	

def show

end

def edit
	
end

def update
	
end

def destroy
  @shop = Shop.find(params[:id])
  @shop.destroy
  redirect_to profile_path(@shop.user.id)
 end	
	


private

def shop_params
    
  params.require(:shop).permit(:shop_name,:shop_type,:shop_city,:shop_timeing,:delivery,:min_order,:description,:shop_image,business_day:[])
    
end

def find_shop

  @shop = Shop.find(params[:id])

end

 end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homecomments_helper.rb
module HomecommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/shopcomments_helper.rb
module ShopcommentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/homes/_form.html.erb
 

 
 <h4 class="text-center"><a class="w3-btn w3-green" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Share product information</a></h4>

<div class="col">
<div class="collapse multi-collapse" id="multiCollapseExample1">
<div class="card card-body">
        
<%=simple_form_for @home, url: homes_path, html: { multipart: true } do |f| %>


<%= f.text_field :product_name,:maxlength=>"50",placeholder:'Prod or biz Name' ,class: "form-control"%></br>
<%= f.label :market_type,"Market type"%>&nbsp;-&nbsp;
<%= f.radio_button :market_type,'Local'%>Local&nbsp;
<%= f.radio_button :market_type,'Global'%>Global
</br>

<%= f.text_area :description,:maxlength=>"10000",placeholder: 'Prod or biz Description',class: "form-control" %></br>

<%= f.label :Add_image,'Product Image'%>
<%= f.file_field :homeimage%> </br>

<p class="text-center"><%= f.submit"Publish", :title => "Name,Post,market type,Description can't be blank", :rel => 'tooltip',class: "w3-btn w3-green"%></p>

<%end%>


</div>
 </div>
  </div>

app/views/homes/_search.html.erb
<div id="landing-search-input">
    <div class="row">
        <div class="col-md-12">
           <%= form_with url: homes_path, local: true, method: :get, html: { class: "form-inline" } do |form| %>
               <div class="row form-group">
                  <div class="col-sm-7">
                    <%= form.text_field :search, placeholder: "Search Product or Business Name", size: 40, data: { behavior: "autocomplete" }, class: "form-control" %>
                  </div>
                  <div class="col-sm-1 col-md-offset-1">
                  	<%=form.button (fa_icon "search", text: "Search"), class: "w3-btn w3-blue-grey" %>

                  </div>
                </div>
           <% end %>
       </div>
    </div>
</div>

app/views/homes/_search_user.html.erb
<div id="landing-search-input">
    <div class="row">
        <div class="col-md-12">
           <%= form_with url: new_home_path, local: true, method: :get, html: { class: "form-inline" } do |form| %>
               <div class="row form-group">
                  <div class="col-sm-7">
                    <%= form.text_field :search, placeholder: "user", size: 40, data: { behavior: "autocomplete" }, class: "form-control" %>
                  </div>
                  <div class="col-sm-1 col-md-offset-1">
                  	<%=form.button (fa_icon "search", text: "Search"), class: "w3-btn w3-blue-grey" %>

                  </div>
                </div>
           <% end %>
       </div>
    </div>
</div>

app/views/homes/edit.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1 class="new-msg-header">Edit post</h1>
	<%= render 'form' %>
</div>

app/views/homes/index.html.erb
<% if user_signed_in? %>
<div class="col-md-6 col-md-offset-3 share-product-btn">
  <%= render 'form' %>
  </div>
  <%else%>
<div class="col-md-12">
  <div class="head">
  
 <h7>Sign In to share product or business information</h7>
 </div>
</br>
</div>
<%end%>

<div class="col-md-12">

<div class="row">

<div class="col-md-6">  
  <div class="searchbar"><%= render 'search' %></div>
</div>

<div class="col-md-3 col-md-offset-3 w3-hide-small w3-hide-medium"> 
<div class="w3-panel w3-card-2 w3-responsive"> 

<h4 class="text-center">users</h4>
<h5 class="text-center"><%=link_to "view all user",new_home_path,class: "w3-button w3-blue-grey"%></h5>

</div>
</div>

</div>
</div>

<div class="col-md-12">
<div class="row">

<div class=col-md-9>	

<%@homes.each do |home| %>
<div class="col-md-6">
<div class="w3-container w3-margin-bottom">
<div class="w3-panel w3-card w3-responsive cardhome">
</br>
<h6><b>Name : </b><%=link_to home.user.name.first(20).capitalize, profile_path(home.user.id),class: "w3-text-blue"%></h6>
  <p><b> country : </b><%=home.user.country.first(14).capitalize %>

  / <%=home.user.business_type.capitalize%> </p>

      <%if home.homeimage.present?%>

      <%=image_tag home.homeimage.url(:medium),alt:"product_image", :width => '50%', class:"w3-hover-opacity"%>
      <%else%>
      <%=image_tag("shopprod_image/n4.jpg",:size => "150x150")%>
 
      <%end%>	
 <p class="card-text">       
        <p><b>Product / Biz: </b><%=home.product_name.first(34).capitalize%></p>

        <p><b>Market Type : </b><%=home.market_type%></p>
        
        <p><%= home.description.first(230).capitalize%></p>
        
        <p>(<%=home.homecomments.count%>) Comment</p>
  </p> 
        <%= link_to "View Post", home,class: "w3-button w3-blue-grey" %>

      </div>
  </div>  
</div>
<%end%>   

</div>


<div class="col-md-3 w3-hide-small w3-hide-medium">



<%@users.each do|user|%>

<div class="w3-panel w3-card w3-responsive">

<%if user.profiles.length == 0%>
<div class="text-center"><%=link_to image_tag("shopprod_image/person.png",width: "60px",class: 'img-circle'),profile_path(user.id)%></div>
<%end%>

<% user.profiles.each do |profile| %>
<div class="text-center"><%=link_to (image_tag profile.profile_image.url(:medium),:size => "60x60",:crop =>:fill,class: 'img-circle'),profile_path(user.id)%></div>
<%end%>
<div class="text-center"><%=link_to user.name.first(20).capitalize,profile_path(user.id),class: "w3-text-blue"%></div>
<div class="text-center"><%=user.business_type.capitalize%></div>
<div class="text-center"><%=user.country.first(11)%> </div>

</div>
<%end%>


</div>	




</div>
</div>

app/views/homes/new.html.erb
<div class="col-md-6">  
  <div class="searchbar"><%= render 'search_user' %></div>
</div>

<div class="w3-container">


<%@users.each do|user|%>
<div class="col-md-3">
<div class="w3-panel w3-card w3-responsive carduser">

<%if user.profiles.length == 0%>
<div class="text-center"><%=link_to image_tag("shopprod_image/person.png",width: "60px",class: 'img-circle'),profile_path(user.id)%></div>
<%end%>

<% user.profiles.each do |profile| %>
<div class="text-center"><%=link_to (image_tag profile.profile_image.url(:medium),:size => "60x60",:crop =>:fill,class: 'img-circle'),profile_path(user.id)%></div>
<%end%>
<div class="text-center"><%=link_to user.name.first(20).capitalize,profile_path(user.id),class: "w3-text-blue"%></div>
<div class="text-center"><%=user.business_type.capitalize%></div>
<div class="text-center"><%=user.country.first(11)%> </div>

</div>
</div>
<%end%>
</div>

app/views/messages/new.html.erb
</br>
<div class="col-md-9">
<div class="w3-container w3-margin-bottom">

 <div class="text-center"><%= link_to "Back",shops_path,class: "w3-btn w3-green"%></div>
</div>
</div>

<div class="col-md-9 col-md-offset-1">
<div class="w3-container w3-margin-bottom">

<%= form_for @message, html: {class: "pure-form"} do |s|%>

<div class="col-md-3">
	<div class="field">
	<%= s.label :name,"Shop Name"%></br>
   <%= s.text_field :keywords,placeholder:'Ex - ABC book retail shop, ABC toy manufacturer'%>
    </div>
 </div>    
 
  <div class="col-md-3">
	<div class="field">
	<%= s.label :city,"Shop City"%></br>
	<%=s.text_field :keywords2,placeholder:'Ex - Delhi'%>
  </div>
  </div>
    
   <div class="col-md-3">
    <div class="field">
    <%= s.label :shop_type,"Shop Type"%></br>
    <%=s.text_field :keywords3,placeholder:'Ex - Book Shop,Grocery Shop,Mobile Manufacturer,Medical Shop'%>
    </div>
    </div>

   </br>
    <div class="col-md-1">
  <div class=""><%=s.submit "search",class: "w3-button w3-blue-grey"%></div>
    </div>

	<%end%>
 

</div>
</div>

app/views/products/_form.html.erb
 
 <h4 class="text-center"><a class="w3-btn w3-green" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Add Product</a></h4>

<div class="col">
<div class="collapse multi-collapse" id="multiCollapseExample1">
<div class="card card-body">
        
<%=simple_form_for @product, url: products_path, html: { multipart: true } do |f| %>

<%= f.label :product_name,"Product Name" %>
<%= f.text_field :product_name,:maxlength=>"24",class: "form-control"%>
</br>

<%= f.label :Product_price,"product Price" %> 
<%= f.text_area :product_price,:maxlength=>"15",class: "form-control"%>
</br>


<%= f.label :product_image,'Product Image'%>
<%= f.file_field :product_image%> </br>

<p class="text-center"><%= f.submit"Publish", :title => "Name,Post,market type,Description can't be blank", :rel => 'tooltip',class: "w3-btn w3-green"%></p>

<%end%>


</div>
 </div>
  </div>

app/views/profiles/_form.html.erb
<div class="col-md-7 col-sm-7">
<div class="w3-panel w3-card w3-responsive">
<div class="w3-container w3-margin-bottom">

<h3>Add photo</h3>

<%=simple_form_for @profile, url: profiles_path, html: { multipart: true } do |f| %>

<%= f.label :profile_image,'Your Photo'%></br>
 <%= f.file_field :profile_image%></br>

<%=f.label :date_of_birth,'Birth Year'%></br>
<%= f.date_field :date_of_birth,:order => [:day, :month, :year]%></br>

</br>
<%= f.submit"Upload Image",:title => "Your photo, Birth year can't be blank", :rel => 'tooltip',class: "w3-btn w3-green"%>

<%end%>


</div>
</div>
</div>

app/views/profiles/new.html.erb
<div class="col-md-8 col-md-offset-2">
<div class="panel panel-default">

	

	<%=render 'form'%>

</div>
</div>

app/views/profiles/show.html.erb
<div class="col-md-12 col-sm-12">
<div class="row">	

<div class="col-md-4 col-sm-4">
<div class="w3-panel w3-card w3-responsive">
<div class="w3-container w3-margin-bottom">

<%if @user.profiles.length == 0%>
<%= image_tag("shopprod_image/person.png",width: "80px",class: 'img-circle')%>
<%end%>

<%@user.profiles.limit(1).each do |profile|%>
</br>
<p><%= image_tag profile.profile_image.url(:medium),:size => "100x100", :crop =>:fill,class: 'img-circle'%></p>
<p>Birth Year : <%=profile.date_of_birth%><p>
<% if current_user == profile.user%>  
<p><%= link_to "Delete", profile_path(profile), method: :delete, data: { confirm: "Are you sure?"},class: "text-danger"%></p>
<%end%>
<%end%>

<% if user_signed_in? %> 
<% if current_user.id == @user.id%>
<%if @user.profiles.length == 0%>
<p><%=link_to"Add photo",new_profile_path,class: "w3-btn w3-green" %></p>
<%end%>
<%end%>
<%end%>
<h5><b><%=@user.name.first(10).capitalize%></b></h5>
<p><%=@user.business_type.capitalize%> /
<%=@user.country.first(15).capitalize%></p>

</div>
</div>
</div>


<div class="col-md-4 col-sm-4">
<div class="w3-panel w3-card w3-responsive">
<div class="w3-container w3-margin-bottom">


<%if @user.shops.length == 0%>
<% if user_signed_in? %> 
<% if current_user.id == @user.id%>
<div class="w3-responsive">
<h5 class="w3-button w3-border w3-hover-blue-grey"><%=link_to"Add shop Name",new_shop_path%></h5>
</div>

<%end%>
<%end%>
<%end%>

   <%@user.shops.each do |shop|%>
   <h5><b><%=shop.shop_name%></b></h5>
   <p><%=shop.shop_type%></p>
   <p><%=shop.shop_city%></p>
   <%end%>

   <%=link_to " Shop ", product_path(@user.id),class: "w3-btn w3-green"%>

   <% if user_signed_in? %> 
<% if current_user.id == @user.id%>
   <%=link_to " Dashboard", profiles_path,class: "w3-btn w3-blue-grey"%>
<%end%>
<%end%>


</div>
</div>
</div>

</div>
</div>


<div class="col-md-12 col-sm-12">
<div class="row">	
<div class="w3-panel w3-card w3-responsive">
<div class="w3-container w3-margin-bottom">

<h4><b>Shop Information</b></h4>
<%if @user.shops.length == 0%>
<% if user_signed_in? %> 
<% if current_user.id == @user.id%>
<h5 class="w3-button w3-border w3-hover-blue-grey"><%=link_to"Add shop Name to recognize.",new_shop_path%></h5>
<%end%>
<%end%>
<%end%>

<%@user.shops.each do |shop|%>
<div class="col-md-4">
</br>
<%if @user.profiles.length == 0%>
       <%=image_tag("shopprod_image/shop.jpg",:size => "150x150")%>

<%else%>

<%= image_tag shop.shop_image.url(:medium),:size => "200x200", :crop =>:fill%>
<%end%>


</div>
<div class="col-md-4 col-sm-4">

     <h5><%=shop.shop_name%></h5>
     <p><%=shop.shop_type%></p>
     <p><%=shop.shop_city%></p>
     <p><%=shop.business_day%></p>
     <p><%=shop.shop_timeing%></p> 
 </div> 
 <div class="col-md-4 col-sm-4">
    
     <p><%=shop.delivery%></p>
     <p><%=shop.min_order%></p>
     <p><%=shop.description%></p> 
 </br>
<% if current_user == shop.user%> 
<%= link_to "Delete", shop_path(shop), method: :delete, data: { confirm: "Are you sure?" },class: "w3-button w3-red" %>
<%end%>
</div>
<%end%>

</div>
</div>
</div>
</div>


<div class="col-md-12 col-sm-12">
<div class="row">	
<div class="w3-panel w3-card w3-responsive">
<div class="w3-container w3-margin-bottom">

<h4><b>Products Information</b></h4>
<%if @user.products.length == 0%>
<% if user_signed_in? %> 
<% if current_user.id == @user.id%>
<h5 class="w3-button w3-border w3-hover-blue-grey"><%=link_to"Add Products to your shop.",product_path(@user.id)%></h5>
<%end%>
<%end%>
<%end%>
<%@user.products.each do |product|%>

<div class="col-md-3 col-sm-3">
<div class="panel panel-default">
<div class="w3-container w3-margin-bottom">
<%if @user.profiles.length == 0%>
       <%=image_tag("shopprod_image/product.jpg",:size => "150x150")%>

<%else%>
 <div class="text-center"><%=image_tag("shopprod_image/product.jpg",:size => "180x180")%></div>
<%end%>
  


    <p>product : <%=product.product_name%></p>
    <p>Price : <%=product.product_price%></p> 
<% if current_user == product.user%> 
<p><%= link_to "Delete",product_path(product), method: :delete, data: { confirm: "Are you sure?" },class: "w3-button w3-red" %></p>
<%end%>
</div>
</div>
</div>
<%end%>

</div>
</div>
</div>
</div>

</div>

app/views/shops/_form.html.erb
<%= simple_form_for @shop, url: shops_path, html: { multipart: true } do |f|%>

<%= f.label :Shop_Name,"Shop Name(Full shop name)" %>
<%= f.text_field :shop_name,:maxlength=>"40",placeholder:'Ex - ABC book retail shop, ABC toy manufacturer',class: "form-control"%>
</br>

<%= f.label :Shop_City,"Shop City" %>
<%= f.text_field :shop_city,:maxlength=>"30",placeholder:'Ex - Delhi ',class: "form-control"%>
</br>

<%= f.label :Shop_Type,"Shop Type" %>
<%= f.text_field :shop_type,:maxlength=>"40",placeholder:'Ex - Book Shop,Grocery Shop,Mobile Manufacturer,Medical Shop',class: "form-control"%>
</br>

<%= f.label :About_Shop,"About Shop" %> 
<%= f.text_area :description,:maxlength=>"200",placeholder:'Describe About Your Shop',class: "form-control"%>
</br>

<%= f.label :Shop_Timeing,'Shop Open and Closed Time' %>
<%= f.text_field :shop_timeing,:maxlength=>"37",placeholder:' Ex-Morning 9AM to Evening 6PM ',class: "form-control"%></br>

<%= f.label :Min_Order,'Min Order' %>
<%= f.text_field :min_order,:maxlength=>"20",placeholder:'Ex - 3 Box',class: "form-control"%></br>



<%= f.label :Delivery,'Delivery Time' %>
<%= f.text_field :delivery,:maxlength=>"20",placeholder:'Ex - 2 Hours',class: "form-control"%></br>

<%= f.label :Shop_image,'Shop/Office front Image'%>
<%= f.file_field :shop_image%></br>

<%= f.submit"Add Shop Information",class: "w3-btn w3-green"%></b>
</br>
</br>
</br>
<%end%>

app/views/shops/_search.html.erb
<div id="landing-search-input">
    <div class="row">
        <div class="col-md-12">
           <%= form_with url: shops_path, local: true, method: :get, html: { class: "form-inline" } do |form| %>
               <div class="row form-group">
                  <div class="col-sm-7">
                    <%= form.text_field :search, placeholder: "Search Shop Name", size: 40, data: { behavior: "autocomplete" }, class: "form-control" %>
                  </div>
                  <div class="col-sm-1 col-md-offset-1">
                  	<%=form.button (fa_icon "search", text: "Search"), class: "w3-btn w3-blue-grey" %>

                  </div>
                </div>
           <% end %>
       </div>
    </div>
</div>

app/views/shops/index.html.erb
<% if user_signed_in? %>
  <%else%>
<div class="col-md-12">
  <div class="head">
  
 <h7>Sign In to create a Shop </h7>

 </div>
</div>
<%end%>
</br>


<div class="col-md-10 col-md-offset-1 w3-container">    
<div class="searchbar"><%= render 'search' %></div>
<h7><b><%=link_to"Filter Search",new_message_path%></b></h7>
</div>
</div>

<div class="col-md-10 col-md-offset-1">

<%@shop.each do |shop|%>
<div class="panel panel-default">
<div class="row">

<div class="col-md-2">
<div class="w3-container w3-margin-bottom">

    <h6 class="w3-text-green"><b><%=shop.shop_name.first(30)%></b></h6>
 <%if shop.shop_image.present?%>
<p><%= image_tag shop.shop_image.url(:thumb),:size => "150x150", :crop =>:fill%></p>

      <%else%>
       <%=image_tag("shopprod_image/shop.jpg",:size => "150x150")%>

      <%end%>       

<p><%= link_to "View shop",product_path(shop.user.id),class: "w3-btn w3-green" %></p>

</div>
</div>
<div class="col-md-9">
<div class="w3-container w3-margin-bottom">
     
    <h6><b> Name : </b><%=link_to shop.user.name.first(30).capitalize, profile_path(shop.user.id),class: "w3-text-blue"%></h6>
    <p>  <%=shop.user.country%> /
    <%=shop.user.business_type%></p>
    <p class="text-muted"><%= time_ago_in_words(shop.created_at) %> ago</p>

    <h6><b>Type : </b><%=shop.shop_type%></h6>
    <p><b>City : </b><%=shop.shop_city%></p>
    <p><b>delivery : </b><%=shop.delivery%></p>
    
    <p class="text-muted"><%=shop.description%></p> 
</div>
</div>

</div>
</div>
<%end%>
</div>

app/views/shops/new.html.erb
<div class="col-md-8 col-md-offset-2">



<%=render 'form'%>




</div>